[book]
authors = ["zheng"]
language = "en"
multilingual = false
src = "src"
title = "xx"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/zhengw0426/mybook"
