name: CI (main)

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/install-action@mdbook
      - name: patch for gh-pages build
        run: mv rocketmq/theme/head.hbs._ rocketmq/theme/head.hbs
      - uses: actions/upload-pages-artifact@v1
        with:
          path: rocketmq/book
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    if: github.repository == 'zhengw0426/mybook'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
